### PR TITLE
Set default language to READTHEDOCS_LANGUAGE env var

### PR DESCRIPTION
**Pull request by takos22**

### CODE REVIEW

**Review by humitos — COMMENTED** [review]
LGTM! Thanks. Can you add a test case for this? Thanks.

**Comment by takos22** [comment]
Should I update the docs of `notfound_urls_prefix`, `notfound_default_language` and `notfound_default_version` to mention the environment variables?

**Comment by humitos** [comment]
> Should I update the docs of `notfound_urls_prefix`, `notfound_default_language` and `notfound_default_version` to mention the environment variables?

Yeah. We should reflect this change in the "Default" value mentioned in the docs. Thanks!

**Review by humitos — APPROVED** [review]
Thank you! ❤️

**Pull request merged**
